
version: "3" 
services: 
  mongodb:
    image: mongo:4.4.18
    restart: always
    ports:
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
#    volumes:
#       - ./volume/data:/data/db:rw  # 현재 경로 하위에 생성하면 ./mongo-data:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=mongo
      - ME_CONFIG_BASICAUTH_PASSWORD=mongo
    depends_on:
      - mongodb

  redis-stack:
    image: redis/redis-stack:6.2.6-v7-arm64
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
